services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=project-control'
      - 'MYSQL_PASSWORD=joelm2003'
      - 'MYSQL_ROOT_PASSWORD=joelm2003'
      - 'MYSQL_USER=joelmalacas'
    ports:
      - '3307:3306'
