spring.application.name=Project-Control
spring.docker.compose.enable=false
spring.session.store-type=none
server.error.include-message=always

# Configuração da Datasource (MySQL Remoto)
spring.datasource.url=jdbc:mysql://192.168.1.81:3307/project_control?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=joelmalacas
spring.datasource.password=joelm2003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuração do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect